force-app/main/default/objects/Interaction__c/Interaction__c.object-meta.xml
<CustomObject>
    <label>Interaction</label>
    <nameField>
        <label>Interaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interaction__c/fields/Attendees__c.field-meta.xml
<CustomField>
    <fullName>Attendees__c</fullName>
    <label>Attendees</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Logger__c.field-meta.xml
<CustomField>
    <fullName>Logger__c</fullName>
    <label>Logger</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InteractionTriggerHandler.cls
public with sharing class InteractionTriggerHandler {
    public static void isBeforeUpdate(List<Interaction__c> intList){
        List<Contact> conList = new List<Contact>([SELECT id, Name FROM Contact]);
        for(Interaction__c i : intList){
            for(Contact c : conList){
                if(c.name == i.Attendees__c){
                    i.Logger__c = 'found';
            }
         }
      }
   }
}